[package]
name = "cisco7-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
wasm = ["dep:wasm-bindgen"]

[profile.release]
codegen-units = 1
lto = true
strip = true

[dependencies]
wasm-bindgen = { version = "0.2.93", optional = true }
